# This is the _development_ version of the Dockerfile, useful for testing the
# latest versions of dcrd and dcrros and also used while developing the docker
# images themselves.

# Stage 1: Build the bins in a golang image.
FROM golang:1.19-buster AS builder

# Build the latest compatible dcrd and dcrctl. Comment the checkout lines to use
# the latest master.
RUN git clone https://github.com/decred/dcrd
RUN (cd dcrd && git checkout fc017ce3bb3bba23d5a599eb948c1b74ea54b4f5)
RUN (cd dcrd && go install .)
RUN git clone https://github.com/decred/dcrctl
RUN (cd dcrctl && git checkout release-v1.7.5)
RUN (cd dcrctl && go install .)

# Build from the current dir.
copy . dcrros
RUN (cd dcrros && go install .)

# Stage 2: Build the final image starting from a cleaner base.
FROM ubuntu:latest

# Install ca-certificates so dcrd can reach the network seeders.
RUN apt-get update
RUN apt-get install -y --no-install-recommends ca-certificates
RUN update-ca-certificates

# Copy the previously built bins.
COPY --from=builder /go/bin/dcrd bin/dcrd
COPY --from=builder /go/bin/dcrctl bin/dcrctl
COPY --from=builder /go/bin/dcrros bin/dcrros

# According to Rosetta's documentation, all data should be in /data.
WORKDIR /data

# Expose dcrros and dcrd ports for mainnet, testnet and simnet. Each line is:
# 	dcrros    dcrd-p2p  dcrd-rpc
EXPOSE  9128/tcp  9108/tcp  9109/tcp
EXPOSE 19128/tcp 19108/tcp 19109/tcp
EXPOSE 29128/tcp 19556/tcp 18555/tcp

# The main executable for this is dcrros, running dcrd in "embedded" mode:
# dcrros runs dcrd and controls the lifetime of its process. Once dcrros is
# commanded to stop, it stops the underlying dcrd.
ENTRYPOINT ["dcrros", \
	"--appdata=/data/dcrros", \
	"--rundcrd=dcrd", \
	"--dcrdextraarg=\"--appdata=/data/dcrd\"", \
	"--dcrdcertpath=/data/dcrd/rpc.cert" ]
